#!/usr/bin/env bash
#
# Combine two single-arch XeniOS.app bundles into one universal bundle.
# Run after both arm64 and x86_64 builds complete. Similar to the lipo step
# in .github/workflows/CI.yml but meant for interactive dev use.
#
# Usage:
#   tools/build-universal-macos.sh [arm64_app] [x86_64_app]
# Defaults assume the conventional layout: build/ for arm64, build-x64/ for
# x86_64, Release config.

set -euo pipefail

arm64_app=${1:-build/bin/macOS/Release/XeniOS.app}
x86_64_app=${2:-build-x64/bin/macOS/Release/XeniOS.app}

for app in "$arm64_app" "$x86_64_app"; do
  if [[ ! -d "$app" ]]; then
    echo "error: app bundle not found: $app" >&2
    exit 1
  fi
done

arm64_exe="$arm64_app/Contents/MacOS/XeniOS"
x86_64_exe="$x86_64_app/Contents/MacOS/XeniOS"

# Returns a path containing only the requested arch. If the input is already
# thin and matches, returns the original path; if it's fat (e.g. left over from
# a previous run of this script that lipo'd in place), extracts the slice to a
# temp file so the next lipo doesn't see duplicate archs.
thin_input() {
  local exe=$1
  local want=$2
  local out=$3
  local archs
  archs=$(lipo -archs "$exe")
  if [[ "$archs" != *"$want"* ]]; then
    echo "error: $exe is '$archs', expected '$want'." >&2
    echo "       Reconfigure that build dir with -DCMAKE_OSX_ARCHITECTURES=$want." >&2
    exit 1
  fi
  if [[ "$archs" == "$want" ]]; then
    printf -v "$out" '%s' "$exe"
  else
    local tmp
    tmp=$(mktemp -t XeniOS."$want")
    lipo -thin "$want" "$exe" -output "$tmp"
    printf -v "$out" '%s' "$tmp"
  fi
}
thin_input "$arm64_exe" arm64 arm64_input
thin_input "$x86_64_exe" x86_64 x86_64_input

# Only the main Mach-O is merged
# Fail loud if anything else diverges so we don't silently create a
# bundle where resources don't match one of the slices.
# xenia.log is a runtime drop (the app cwd is Contents/MacOS), and
# _CodeSignature is regenerated by the codesign call below.
if ! diff -r --brief \
    --exclude=XeniOS \
    --exclude=xenia.log \
    --exclude=_CodeSignature \
    "$arm64_app/Contents" "$x86_64_app/Contents"; then
  echo "error: bundles differ outside Contents/MacOS/XeniOS" >&2
  exit 1
fi

tmp=$(mktemp -t XeniOS.universal)
lipo -create "$arm64_input" "$x86_64_input" -output "$tmp"
mv "$tmp" "$arm64_exe"

info=$(lipo -info "$arm64_exe")
echo "$info"
if ! grep -q arm64 <<<"$info" || ! grep -q x86_64 <<<"$info"; then
  echo "error: lipo result missing an arch" >&2
  exit 1
fi

# lipo invalidates the linker-applied ad-hoc signature; arm64 refuses to
# launch unsigned, so re-sign ad-hoc.
codesign --force --sign - "$arm64_app"

echo "universal bundle: $arm64_app"
